### ISSUE TITLE
module 'tensorflow.contrib.estimator' has no attribute 'LinearEstimator'

### ISSUE THREAD

**Issue by IndoorsNumber31** [GaoQ1/rasa_nlu_gq#12]
在rasa_nlu_gao==0.13.4版本的原代码上使用rasa_nlu_gao\classifiers\embedding_bert_intent_estimator_classifier.py 组件会遇到这个错误：

Traceback (most recent call last):
  File "F:\Program Files\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Program Files\Python36\Lib\runpy.py", line 85, in _run_code
  File "F:\rasa_nlu_gq\rasa_nlu_gao\train.py", line 175, in <module>
    num_threads=cmdline_args.num_threads)
  File "F:\rasa_nlu_gq\rasa_nlu_gao\train.py", line 150, in do_train
    interpreter = trainer.train(training_data, **kwargs)
  File "F:\rasa_nlu_gq\rasa_nlu_gao\model.py", line 196, in train
    **context)
  File "F:\rasa_nlu_gq\rasa_nlu_gao\classifiers\embedding_bert_intent_estimator_classifier.py", line 238, in train
    self.estimator = tf.contrib.estimator.LinearEstimator(
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'LinearEstimator'

操作系统是WIN10 64位 家庭中文版 1809
TensorFlow的版本是：1.13.1

Name: tensorflow
Version: 1.13.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: d:\python\3.6\chatbot\lib\site-packages
Requires: keras-applications, tensorflow-estimator, tensorboard, keras-preprocessing, six, absl-py, grpcio, wheel, numpy, gast, astor, termcolor, protobuf
Required-by: rasa-core

**Comment by GaoQ1** [comment]
额，这个组件是别人贡献的，我生产中还没用。 @weizhenzhao 你看下呢

**Comment by weizhenzhao** [comment]
Hi @IndoorsNumber31 

把那个tensorflow 版本降低到1.12.0就可以
pip install --upgrade tensorflow==1.12.0 -i https://mirrors.aliyun.com/pypi/simple

Thanks
weizhen

**Comment by IndoorsNumber31** [comment]
谢谢 @GaoQ1 @weizhenzhao
