### ISSUE TITLE
The number of samples is too large to be trained

### ISSUE THREAD

**Issue by Growing-bison** [GaoQ1/rasa_nlu_gq#13]
**Rasa NLU version**:
rasa-core                         0.12.4     
rasa-core-sdk                     0.12.2     
rasa-nlu                          0.13.8     
rasa-nlu-gao                      0.2.7      
sklearn-crfsuite                  0.3.6      
sklearn-pandas                    1.8.0  
tensorflow                        1.10.0

**Operating system** (windows, osx, ...):
ubuntu 18.04.1 LTS

**Content of model configuration file**:
```yml

language: "zh"
  
pipeline:
- name: "tokenizer_jieba"
- name: "bert_vectors_featurizer"
  #ip: '172.16.10.46'
  port: 5555
  port_out: 5556
  show_server_config: True
  timeout: 10000

- name: "ner_crf"
- name: "jieba_pseg_extractor"
  part_of_speech: ["nr", "ns", "nt"]
- name: "intent_featurizer_count_vectors"
  OOV_token: oov
  token_pattern: '(?u)\b\w+\b'
- name: "intent_classifier_tensorflow_embedding_bert"
  intent_tokenization_flag: True
  intent_split_symbol: "+"

```

**Issue**:
**When using the  1860 samples , it was successful. However, when using 3065 samples,  it was failed. The feedback listed as follows:**

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/train.py", line 175, in <module>
    num_threads=cmdline_args.num_threads)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/train.py", line 150, in do_train
    interpreter = trainer.train(training_data, **kwargs)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/model.py", line 196, in train
    **context)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/classifiers/embedding_bert_intent_classifier.py", line 339, in train
    self.drop_out:self.droprate}
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must be broadcastable: logits_size=[256,28] labels_size=[256,22]
     [[Node: softmax_cross_entropy_with_logits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConvNet/dense_layer_dense/BiasAdd, softmax_cross_entropy_with_logits/Reshape_1)]]


Caused by op 'softmax_cross_entropy_with_logits', defined at:
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/train.py", line 175, in <module>
    num_threads=cmdline_args.num_threads)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/train.py", line 150, in do_train
    interpreter = trainer.train(training_data, **kwargs)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/model.py", line 196, in train
    **context)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu_gao/classifiers/embedding_bert_intent_classifier.py", line 307, in train
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits_train, labels=self.b_in)) + tf.losses.get_regularization_loss()
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1879, in softmax_cross_entropy_with_logits_v2
    precise_logits, labels, name=name)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 7209, in softmax_cross_entropy_with_logits
    name=name)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()


InvalidArgumentError (see above for traceback): logits and labels must be broadcastable: logits_size=[256,28] labels_size=[256,22]
     [[Node: softmax_cross_entropy_with_logits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConvNet/dense_layer_dense/BiasAdd, softmax_cross_entropy_with_logits/Reshape_1)]]
```

The additional samples is also successful to be trained.
Looking forward to your respond. Thank you.

**Comment by GaoQ1** [comment]
it seems logits size isn't equal to labels size

**Comment by Growing-bison** [comment]
Thanks. I had solved it. The reason is that I set up the wrong config.yml.
